Lagt til ekstern behandling.
navikt/familie-tilbake pull request #10
Opened 2021-01-20 13:10 UTC by bent-lorentzen

2021-01-20 14:44 UTC, haldersaikat requested changes

2021-01-20 14:44 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/domain/EksternBehandling.kt
> +                             val aktiv: Boolean = true,
Vi trenger eksternUuid også som er uuid til fagsystemet

2021-01-20 14:44 UTC, haldersaikat commented on src/main/resources/db/migration/V2__ekstern_behandling.sql
> +    opprettet_tid TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
Vi trenger eksternUuid også som er uuid til fagsystemet

2021-01-20 14:44 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/domain/EksternBehandling.kt
> +                             val aktiv: Boolean = true,
Trenger vi behandlingId kolon her?

2021-01-20 15:00 UTC, bent-lorentzen commented on src/main/resources/db/migration/V2__ekstern_behandling.sql
> +    opprettet_tid TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
eksternId er fjernet på din forespørsel.

2021-01-20 16:01 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/domain/EksternBehandling.kt
> +                             val aktiv: Boolean = true,
unnskyld, det var min feil. Jeg tenkte eksternId er samme som henvisning. Henvisning er faktisk behandlingId til fagsystemet og eksternId(vi kaller eksternUuid i foreldrepenger) er uuid til fagsystemet. Kan du gjerne legge til eksternId igjen?

2021-01-21 10:13 UTC, haldersaikat approved these changes

2021-01-21 11:28 UTC, merged