Beregning
navikt/familie-tilbake pull request #120
Opened 2021-03-19 11:55 UTC by bent-lorentzen

Endret Periode til å gå fra måned til måned og lagt til beregning.

2021-03-19 15:00 UTC, haldersaikat requested changes

2021-03-19 15:00 UTC, haldersaikat commented on src/test/kotlin/no/nav/familie/tilbake/data/Testdata.kt
> +                                                          resultatkode = Resultatkode.DELVIS_TILBAKEKREVING,
Dette feltet bruker vi ikke. Så kan du bruke testverdi i stedet.

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/service/dokumentbestilling/handlebars/dto/HbPeriode.kt
> +data class HbPeriode(val fom: LocalDate,
Kan denne heten Handlebarsperiode i stedet? Det er enklere å forstå

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
> +                                 val resultatkode: Resultatkode?,
Dette feltet bruker vi ikke. Denne tabellen bruker vi kun for å lagre data som kommer fra økonomi. I fptilbake beregner vi alltid. Det lagres ikke. Hvis det må lagres, da må vi lagre på et annet tabell.

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/config/DatabaseConfig.kt
> -        return JdbcCustomConversions(listOf(KravstatuskodeLesConverter(),
Hvorfor fjerner du KravstatuskodeLesConverter og KravstatuskodeSkrivConverter? Trenger vi ikke den?

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/kravgrunnlag/domain/Kravgrunnlag431.kt
> +                                 val resultatkode: Resultatkode?,
Ikke blande resultatkode i Kravgrunnlagsbeløp433(som kommer fra økonomi) med vedtaks koderesultat

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/beregning/BeregnBeløpUtil.kt
> +        val ytelseBeløp: BigDecimal = beregnBeløp(vurderingsperiode, kravgrunnlagsperiode, grunnlagBeløpPerMåned)
Skulle det hete ytelsesbeløp i stedet?

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/beregning/modell/BeregningResultatPeriode.kt
> +                                    val renteBeløp: BigDecimal? = null,
kan vi kalle det rentebeløp?

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/beregning/modell/BeregningResultatPeriode.kt
> +                                    val tilbakekrevingBeløp: BigDecimal,
tilbakekrevingsbeløp?

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/beregning/modell/BeregningResultatPeriode.kt
> +                                    val skattBeløp: BigDecimal? = null,
skattebeløp??

2021-03-19 15:00 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/beregning/modell/BeregningResultatPeriode.kt
> +                                    val tilbakekrevingBeløpEtterSkatt: BigDecimal? = null,
tilbakekrevingsbeløpEtterSkatt??utbetaltYtelsesbeløp??riktigYtelsesbeløp??

2021-03-22 07:44 UTC, bent-lorentzen commented on src/main/kotlin/no/nav/familie/tilbake/config/DatabaseConfig.kt
> -        return JdbcCustomConversions(listOf(KravstatuskodeLesConverter(),
Vi trenger den ikke, og dette var den eneste  Enumen som hadde en mapper. Blir litta rart å behandle denne ene enumen annerledes enn alle de andre.

2021-03-25 11:21 UTC, haldersaikat approved these changes

2021-03-25 11:27 UTC, merged