implementerte funksjonalitet for å ta behandling av vent. Fikset behandlingskontroll når saksbehandler allerede utførte steg på nytt.
navikt/familie-tilbake pull request #121
Opened 2021-03-19 14:10 UTC by haldersaikat

2021-03-22 11:47 UTC, bent-lorentzen commented on src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
> +        val behandling = behandlingRepository.findByIdOrNull(behandlingId)
findByIdOrThrow

2021-03-22 11:53 UTC, bent-lorentzen approved these changes

2021-03-22 12:09 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/behandling/BehandlingService.kt
> +        val behandling = behandlingRepository.findByIdOrNull(behandlingId)
ja, jeg kan bruke det. Men det kaster IllegalStateException i stedet som jeg ikke vil ha. Derfor skrev jeg slik.

2021-03-23 08:03 UTC, grmoen-nav requested changes

2021-03-23 08:03 UTC, grmoen-nav commented on src/main/kotlin/no/nav/familie/tilbake/api/BehandlingController.kt
>      fun settBehandlingPåVent(@Valid @RequestBody behandlingPåVentDto: BehandlingPåVentDto) {
Kan du endre til å returnere Ressurs<>?

2021-03-23 08:03 UTC, grmoen-nav commented on src/main/kotlin/no/nav/familie/tilbake/api/BehandlingController.kt
> +    fun taBehandlingAvVent(@PathVariable("behandlingId") behandlingId: UUID) {
Kan du endre til å returnere Ressurs<>?

2021-03-23 12:38 UTC, grmoen-nav approved these changes

2021-03-24 08:26 UTC, merged