Fjerne ubrukt kode, parameter, metode, variabler og retter opp på noe bruk av deprecated metoder
navikt/familie-tilbake pull request #1390
Opened 2024-04-24 11:47 UTC by UyQuangNguyen

2024-04-24 12:08 UTC, ma10s requested changes
Charlie er på vei bort :D

2024-04-24 12:08 UTC, UyQuangNguyen commented
Legges på vent da noe av det som slettes er kode som jobbes på av EF 🙌

2024-04-24 12:10 UTC, charliemidtlyng reviewed
Fint om denne legges _litt på is_ ut uka, slik at @olekvernberg sine endringer vedr. automatisk behandling av under 4xrettsgebyr-brancher kommer inn :)

2024-06-25 08:39 UTC, ma10s approved these changes

2025-02-18 12:00 UTC, fredrikmork commented
Kan gjøre dette på nytt i en annen oppgave.

2025-02-18 12:00 UTC, closed without merging