Ikke overskriv begrunnelse ved automatisk behandling
navikt/familie-tilbake pull request #1432
Opened 2024-05-07 07:53 UTC by olekvernberg

Tar i bruk begrunnelse som blir skrevet av saksbehandler i ef-sak

2024-05-07 08:01 UTC, charliemidtlyng approved these changes

2024-05-07 09:14 UTC, ma10s commented on src/main/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingService.kt
> +                begrunnelse = behandling.begrunnelseForTilbakekreving
Stemmer denne for Constants.AUTOMATISK_SAKSBEHANDLING_BEGUNNLESE ?

2024-05-07 09:16 UTC, ma10s commented on src/main/kotlin/no/nav/familie/tilbake/faktaomfeilutbetaling/FaktaFeilutbetalingService.kt
> +                begrunnelse = behandling.begrunnelseForTilbakekreving
Denne brukte vi tidligere direkte for de som kjøres automatisk. Vil nok fungere for oss, vi sender jo alltid inn denne, men usikker på hvordan dette vil fungere for BA/KS?

2024-05-07 09:18 UTC, ma10s requested changes
Vet ikke om jeg vil ha endringer, men vil gjerne diskutere denne - kan vi ødelegge for automatiske behandlinger (BA/KS) (ikke 4rg)

2024-05-07 11:15 UTC, charliemidtlyng commented
> Vet ikke om jeg vil ha endringer, men vil gjerne diskutere denne - kan vi ødelegge for automatiske behandlinger (BA/KS) (ikke 4rg)

Tja - kanskje. Isåfall vil jeg heller at vi legger på "Automatisk behandlet\n" istedenfor å fjerne den helt?

2024-05-08 08:36 UTC, ma10s approved these changes

2024-05-08 08:37 UTC, merged