Ikke iverksett to ganger
navikt/familie-tilbake pull request #1443
Opened 2024-05-16 10:47 UTC by olekvernberg

Prøver å løse problem med `sendØkonomivedtakTask` som feiler grunnet:
1. To tasker jobber samtidig og iverksetter hvor den ene fullfører, mens den andre feiler.
2. En task iverksetter. Iverksetting går bra, men det mottas ingen response fordi requestet timer ut. Vi prøver å iverksette på nytt, og det går ikke fordi den allerede er fullført.

Tidligere så koden ut til å prøve å lagre økonomiXmlSendt selv om iverksetting feilet. Dette har aldri fungert, og det har dermed bare blitt lagret kvittering i databasen dersom det iverksettingen har gått fint. I testene så det ut som xml ble lagret, noe som ikke skjer i kjørende kode.

2024-05-16 10:51 UTC, olekvernberg commented on src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt
> +            if (hentOppdragStatus(behandlingId).status == OppdragStatus.KVITTERT_OK) {
Skjuler vi meldingen fra IntegrasjonException i loggene dersom det kastes exception fra hentOppdragStatus?

2024-05-16 10:51 UTC, ma10s commented on src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt
> +            if (hentOppdragStatus(behandlingId).status == OppdragStatus.KVITTERT_OK) {
Skjuler vi IntegrasjonException fra iverksettVedtak dersom hentOppdragStatus feiler? 
Jeg tenker vi kan leve med det, men hva tenker dere andre? Går mot samme system, og det logges litt i oppdragClient.iverksettVedtak?

2024-05-16 11:08 UTC, charliemidtlyng commented on src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt
> +            if (hentOppdragStatus(behandlingId).status == OppdragStatus.KVITTERT_OK) {
Kan jo legge inn en logglinje mellom 87 og 88 hvor vi logger noe ala:

```
logger.warn("Kunne ikke sende request til Økonomi. Sjekker om kvitteringen allerede er OK")
secureLogger.warn("Kunne ikke sende request til Økonomi. Sjekker om kvitteringen allerede er OK", e)
```

?

2024-05-16 11:08 UTC, charliemidtlyng approved these changes

2024-05-16 11:14 UTC, ma10s commented
Nå ble jeg usikker på om oppdragStatus gir oss det vi trenger. Må undersøkes.

2024-05-21 06:48 UTC, ma10s requested changes
Vi må endre litt på denne. Hent status virker ikke, men vi kankanskje beholde endringene i forhold til behandling.erAvsluttet?

2024-05-21 07:46 UTC, ma10s commented on src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt
> +            if (hentOppdragStatus(behandlingId).status == OppdragStatus.KVITTERT_OK) {
Fjerner denne :( - fungerer ikke som forvantet

2024-05-23 11:21 UTC, ma10s commented on src/main/kotlin/no/nav/familie/tilbake/iverksettvedtak/IverksettelseService.kt
> +            if (hentOppdragStatus(behandlingId).status == OppdragStatus.KVITTERT_OK) {
Fjernet

2024-05-23 12:40 UTC, merged