TEA-5832 e2e-profil for å kjøre verdikjedetestester som en del av GHA-pipeline
navikt/familie-tilbake pull request #353
Opened 2021-08-16 11:26 UTC by grmoen-nav

2021-08-16 12:07 UTC, haldersaikat requested changes

2021-08-16 12:07 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/integration/kafka/KafkaProducer.kt
> +class MockKafkaProducer : KafkaProducer {
Hvis det kun  brukes i e2e, kan det kalles E2EKafkaProducer i stedet

2021-08-16 12:07 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/integration/økonomi/ØkonomiConsumer.kt
> +interface ØkonomiConsumer {
Trenger vi en interface her?

2021-08-16 12:07 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/integration/økonomi/ØkonomiConsumer.kt
> +class MockØkonomiConsumer : ØkonomiConsumer {
Hvis det kun brukes i e2e, kan det kalles E2EØkonomiConsumer i stedet

2021-08-17 06:54 UTC, grmoen-nav commented on src/main/kotlin/no/nav/familie/tilbake/integration/familie/IntegrasjonerClient.kt
> +interface IntegrasjonerClient {
Tror eg må bruke interface her. KafkaConfig og KafkaLocalConfig er config-klasser som definerer ulike beans, mens her er det DefaultIntegrasjonerClient og E2EIntegrasjonerClient som er beana.

2021-08-19 09:12 UTC, hensol approved these changes

2021-08-19 09:42 UTC, haldersaikat approved these changes

2021-08-19 09:43 UTC, merged