Setter behandlingstema for EF ytelser
navikt/familie-tilbake pull request #541
Opened 2021-12-13 14:02 UTC by hensol

2021-12-13 14:15 UTC, ViktorGSolberg approved these changes

2021-12-13 14:15 UTC, charliemidtlyng approved these changes
Ser bra ut! 🎉

2021-12-14 08:49 UTC, ma10s requested changes
Tror ikke dette kommer til å fungere - behandlingstype + behandlingstema gir feil fra oppgave. Ikke lovlig kombinasjon.

2021-12-14 09:00 UTC, ma10s commented
Vi sjekker om det er mulig å endre kodeverk for å tillate denne komboen.

2021-12-14 14:19 UTC, hensol commented
> Tror ikke dette kommer til å fungere - behandlingstype + behandlingstema gir feil fra oppgave. Ikke lovlig kombinasjon.

ok, da sletter jeg denne PRen?

2021-12-15 13:48 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/tilbake/oppgave/OppgaveService.kt
> +        Ytelsestype.KONTANTSTØTTE -> null
Den kan slå sammen med linje Ytelsestype.BARNETRYGD,Ytelsestype.KONTANTSTØTTE -> null

2021-12-16 20:57 UTC, closed without merging